name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/slack-news-sentiment-bot:latest

      - name: Run Docker container with environment variables
        run: |
          docker run -d \
            -e SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN \
            -e SLACK_APP_TOKEN=$SLACK_APP_TOKEN \
            -e NEWSAPI_KEY=$NEWSAPI_KEY \
            -e SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID \
            -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/slack-news-sentiment-bot:latest

