name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE: ${{ vars.IMAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.IMAGE }}:latest
          build-args: |
            SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}
            SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}
            NEWSAPI_API_KEY=${{ secrets.NEWSAPI_API_KEY }}

